In [1]:
import sys
import os
import numpy as np
import math
import random
import gym
import gym_maze
import time
from stable_baselines3 import PPO, A2C
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.evaluation import evaluate_policy

d:\anaconda\envs\gym-final\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
time_log = int(time.time())
models_dir = f"models/{time_log}/"
log_dir = "logs"

if not os.path.exists(models_dir):
    os.makedirs(models_dir)
if not os.path.exists(log_dir):
    os.makedirs(log_dir)

In [3]:
env = make_vec_env("maze-warehouse-picks-v0")
env.reset()
model = PPO("MlpPolicy", env, verbose=1, tensorboard_log=f"./warehouse_tensorboard/{time_log}", n_steps= 320, batch_size=64, sde_sample_freq=2 )
# try CNN policy
# try other policy as well
# a larget network / custom policy network
#model = A2C("MlpPolicy", env, verbose=1, tensorboard_log="./warehouse_tensorboard/", n_steps= 300, )

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
version v0.1 warehouse
Env Reseted
Env Reseted
Using cpu device


In [4]:
maze_env = env.envs[0].unwrapped
print('current state:\n', maze_env.state.T)

current state:
 [[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0]
 [ 0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0]
 [ 0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0]
 [ 0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0]
 [ 0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0]
 [ 0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0]
 [ 0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0]
 [ 0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0]
 [ 0  0 -1 -1  0  2 -1 -1  2  0 -1 -1  0  0 -1 -1  0  0]
 [ 0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0]
 [ 0  0 -1 -1  0  2 -1 -1  0  0 -1 -1  0  0 -1 -1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  

In [ ]:
env.reset()
log = env.render()

In [ ]:
TIMESTEPS = 10_000
for i in range(26):
    log = env.render()
    model.learn(total_timesteps=TIMESTEPS, reset_num_timesteps=False, tb_log_name="ppo_first_run",  )
    model.save(f"{models_dir}/{TIMESTEPS*i}")

In [11]:
#model_path_best = './models/1654640298/110000.zip'
#model_best = PPO.load(model_path_best, env=env)

In [ ]:

# Enjoy trained agent
obs = env.reset()

for i in range(25000):
    action, _states = model.predict(obs, deterministic=False)
    obs, rewards, dones, info = env.step(action)

    env.render()